### ISSUE TITLE
facing maven build issue

### ISSUE THREAD

**Issue by subbuvidyasekar** [s-match/s-match-utils#2]
Hi,

I am trying to build the s-match projects(utils, core, logic, and etc).

I am getting the following error message.

[ERROR] Failed to execute goal on project s-match-utils: 
Could not resolve dependencies for project it.unitn.disi:s-match-utils:jar:2.0.0-SNAPSHOT: 
The following artifacts could not be resolved: 
it.unitn.disi:s-match-core:jar:2.0.0-SNAPSHOT,
it.unitn.disi:s-match-wordnet:jar:2.0.0-SNAPSHOT, 
it.unitn.disi:s-match-io:jar:2.0.0-SNAPSHOT, 
it.unitn.disi:s-match-logic:jar:2.0.0-SNAPSHOT, 
it.unitn.disi:s-match-spsm:jar:2.0.0-SNAPSHOT, 
it.unitn.disi:s-match-nlp:jar:2.0.0-SNAPSHOT, 
it.unitn.disi:s-match-nlp-opennlp:jar:2.0.0-SNAPSHOT, 
it.unitn.disi:s-match-nlp-annotation:jar:2.0.0-SNAPSHOT: 
Failure to find it.unitn.disi:s-match-core:jar:2.0.0-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced.

Is this maven issue or it.unitn.disi snapshot issue? i am totally confused.

Please help to solve this problem.

thanks,
vidyasekar

**Comment by autayeu** [comment]
It's a documentation problem. It helps to read the docs ;) Take a look at the [HowToBuild](https://github.com/s-match/s-match-core/wiki/HowToBuild) wiki page.
